name: Multiplatform Build CI

on:
  push:
    branches:
      - 'main'
      - 'dev'
    tags:
      - 'v*'

  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          token: ${{ secrets.GITHUB_TOKEN }}
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build debug APK with Gradle
        run: ./gradlew assembleFossDebug

      - name: Run tests
        run: ./gradlew testFossDebugUnitTest

      - name: Upload debug APK artifact
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: ./androidApp/build/outputs/apk/foss/debug/androidApp-foss-debug.apk

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          token: ${{ secrets.GITHUB_TOKEN }}
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Package DEB archive
        run: ./gradlew packageReleaseDeb

      - name: Upload packaged DEB archive
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: ./desktopApp/build/compose/binaries/main-release/deb/*.deb

      - name: Package RPM archive
        run: ./gradlew packageReleaseRpm

      - name: Upload packaged RPM archive
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: ./desktopApp/build/compose/binaries/main-release/rpm/*.rpm
  
  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          token: ${{ secrets.GITHUB_TOKEN }}
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Package DMG
        run: ./gradlew packageReleaseDmg

      - name: Upload packaged DMG
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: ./desktopApp/build/compose/binaries/main-release/dmg/*.dmg

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          token: ${{ secrets.GITHUB_TOKEN }}
          cache: gradle

      - name: Package EXE
        run: ./gradlew.bat packageReleaseExe

      - name: Upload packaged EXE
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: ./desktopApp/build/compose/binaries/main-release/exe/*.exe

  package-linux-flatpak:
    needs: build-linux
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-24.08
      options: --privileged

    steps:
      - uses: actions/checkout@v6

      - name: Get architecture
        run: |
          echo "ARCH=$(uname -m)" >> $GITHUB_ENV

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: tomato-${{ github.ref_name }}.flatpak
          manifest-path: flatpak/org.nsh07.pomodoro.yml
          cache-key: flatpak-builder-${{ github.sha }}

  package-linux-snap:
    needs: build-linux
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Build Snap
        uses: snapcore/action-build@v1
        id: snapcraft

      - name: Upload packaged Snap
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: ${{ steps.snapcraft.outputs.snap }}

  create-release:
    needs: [ build-linux, package-linux-flatpak, package-linux-snap, build-macos, build-windows ]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v8
        with:
          path: artifacts/

      - name: Create or Update Release Draft
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          files: |
            artifacts/**/*.deb
            artifacts/**/*.rpm
            artifacts/**/*.flatpak
            artifacts/**/*.snap
            artifacts/**/*.dmg
            artifacts/**/*.exe