name: Multiplatform Build CI

on:
  push:
    branches:
      - 'main'
      - 'dev'

  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          token: ${{ secrets.GITHUB_TOKEN }}
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build debug APK with Gradle
        run: ./gradlew assembleFossDebug

      - name: Run tests
        run: ./gradlew testFossDebugUnitTest

      - name: Upload debug APK artifact
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: ./androidApp/build/outputs/apk/foss/debug/androidApp-foss-debug.apk

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          token: ${{ secrets.GITHUB_TOKEN }}
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Package DEB archive
        run: ./gradlew packageReleaseDeb

      - name: Upload packaged DEB archive
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: ./desktopApp/build/compose/binaries/main-release/deb/*.deb

      - name: Package RPM archive
        run: ./gradlew packageReleaseRpm

      - name: Upload packaged RPM archive
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: ./desktopApp/build/compose/binaries/main-release/rpm/*.rpm

  package-linux:
    needs: build-linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Install Flatpak and flatpak-builder
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install --user -y flathub org.freedesktop.Platform//24.08 org.freedesktop.Sdk//24.08 org.freedesktop.Sdk.Extension.openjdk21//24.08

      - name: Build Flatpak
        run: |
          flatpak-builder --force-clean --user --repo=flatpak-repo \
            flatpak-build-dir $GITHUB_WORKSPACE/flatpak/org.nsh07.pomodoro.yml
          flatpak build-bundle flatpak-repo Tomato.flatpak org.nsh07.pomodoro

      - name: Upload packaged Flatpak
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: ./Tomato.flatpak

      - name: Build Snap
        uses: snapcore/action-build@v1
        id: snapcraft

      - name: Upload packaged Snap
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: ${{ steps.snapcraft.outputs.snap }}
  
  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          token: ${{ secrets.GITHUB_TOKEN }}
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Package DMG
        run: ./gradlew packageReleaseDmg

      - name: Upload packaged DMG
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: ./desktopApp/build/compose/binaries/main-release/dmg/*.dmg

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          token: ${{ secrets.GITHUB_TOKEN }}
          cache: gradle

      - name: Package EXE
        run: ./gradlew.bat packageReleaseExe

      - name: Upload packaged EXE
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: ./desktopApp/build/compose/binaries/main-release/exe/*.exe